Container componentの作成
NUTFes/group-manager-2 pull request #1021
Opened 2023-01-19 01:46 UTC by noaikarashi

# 対応Issue

resolve #1010 

# 概要

登録情報を表示するコンテナコンポーネントを作成した。

# 変更ファイル

- user_front/components/Container.vue
-
-

# 画面スクリーンショット等

スクリーンショット
- 
![image](https://user-images.githubusercontent.com/90322124/213335685-c0531237-8ef0-4186-b60d-5c5881c56c7b.png)

ヘッダーと合わせた場合
![image](https://user-images.githubusercontent.com/90322124/213335767-c69eff5a-3139-41a2-8a29-d11fddebea9c.png)

# テスト項目

-
-
-

# 備考

2023-01-19 04:02 UTC, noaikarashi commented
![image](https://user-images.githubusercontent.com/90322124/213352300-7cd5549f-108f-4e59-b94d-f7d166d1a843.png)

2023-01-22 11:09 UTC, ryuseifujisaki commented
![image](https://user-images.githubusercontent.com/50622120/213909410-c8c04c7c-af79-454e-b5e1-06c57d948420.png)

![image](https://user-images.githubusercontent.com/50622120/213909394-8a14a60f-7b7c-4520-bd02-06f53e0c9c5d.png)

いくつか確認したい点があります！
- figmaのデザインと少々違いますが、これは問題ないでしょうか？とりあえずのデザインなんすかね？
- figmaを見るとタブのwidthが100%ですけど、これを見ると50%しかないのは問題ないですかね？

2023-01-22 11:29 UTC, ryuseifujisaki requested changes
デザイン面、コード面含めてレビューしました。確認お願いします。

2023-01-22 11:29 UTC, ryuseifujisaki commented on user_front/components/Container.vue
> +        <a class="bg-gray-100 inline-block py-2 px-4 rounded-t-xl font-semibold hover:bg-gray-200 hover:shadow-lg cursor-pointer">{{ order.title }}</a>
```suggestion
        <a class="title">{{ order.title }}</a>
        ...
        <style>
        .title{
             @apply bg-gray-100 inline-block py-2 px-4 rounded-t-xl font-semibold hover:bg-gray-200 hover:shadow-lg cursor-pointer
        }
         </style>
```

長くなっているものは可読性を考慮すると、@applyを使ってコンポーネント化した方がいいと思います。

2023-01-22 11:29 UTC, ryuseifujisaki commented on user_front/components/Container.vue
> +<script setup>
```suggestion
<script lang="ts" setup>
```
typesciptなので、追加した方がよさそうです。

2023-02-14 01:39 UTC, merged