[add]regist page [fix]Header Footer
NUTFes/group-manager-2 pull request #1030
Opened 2023-01-20 08:19 UTC by TomoeYasuda

# 対応Issue1024

resolve #1024 

# 概要

- 登録ページの作成
- HeaderとFooterの位置固定の修正

# 変更ファイル

-/pages/regist/
-/components/
-

# 画面スクリーンショット等

- `URL`
スクリーンショット

# テスト項目

- 画面の表示の有無と配置が正しく表示されているか
-
-

# 備考

2023-01-22 12:13 UTC, ryuseifujisaki requested changes
コードの修正をお願いします！
わからない点は聞いてください！
あと、具体的に、何をチェックすればいいのかわからないので、もう少し具体的にPR書いてもらえると助かります

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/app.vue
>  </template>
```suggestion
</template>

```
ソースコードにおいて末尾は改行で終わっている方が適切です。
vscodeでは保存時に自動で最後空行を追加する設定があるので、今のうちに設定しちゃいましょう！
[参考記事]
https://qiita.com/Aseiide/items/e66be44c4b7972902063

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/user/index.vue
> +</template>
```suggestion
</template>

```
上記と同じ

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/group/index.vue
> +          </div>
```suggestion
<script lang="ts" setup>
  const formTitle = [
    "name",
    "student id",
    "department",
    "grade",
    "mail adress",
    "phone number",
  ];
</script>
         ...
<div v-for="title in formTitle" :key="title" class="flex">
   <p class="label">{{ title }}</p>
   <input class="form" />
</div>
```
同じ処理してるのでこんな感じにかけます。

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/group/index.vue
> +            <input class="flex-none border-solid border-2" />
```suggestion

`user_front/assets/tailwind.css`
@layer components {
  .label {
    @apply
      flex-none
      text-xl
      pr-5
  }

  .form {
    @apply
    flex-none
    border-solid
    border-2
  }
}

`user_front/pages/regist/group/index.vue`
            <p class="label"</p>
            <input class="form" />
```
同じclassを複数行で使う場合はコンポーネント化した方がよさそうです。

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/group/index.vue
>  </template>
```suggestion
</template>

```
改行追加

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/subrep/index.vue
> +          </div>
上記と同じでtailwindのコンポーネント化と`v-for`を使いましょう

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/user/index.vue
> +          </div>
上記と同じでtailwindのコンポーネント化とv-forを使いましょう

2023-01-22 12:13 UTC, ryuseifujisaki commented on user_front/pages/regist/user/index.vue
> +</template>
```suggestion
</template>

```
空行お願いします

2023-02-02 19:58 UTC, TomoeYasuda commented on user_front/pages/regist/subrep/index.vue
> +          </div>
登録する情報がページごとに違うのでそれぞれ作る時に担当が編集しましょう。

2023-02-02 20:02 UTC, TomoeYasuda commented
ページのから業の追加は終了しました。
登録ページのクラス化や繰り返し文などはページを作る時に作成します。

2023-02-17 07:25 UTC, merged