stageの希望場所のバリデーションを行う
NUTFes/group-manager-2 pull request #1211
Opened 2023-05-19 15:54 UTC by TsubasaOura

# 対応Issue

resolve #1210 

# 概要

stageの希望場所のバリデーションを行った

# 画面スクリーンショット等

![Uploading image.png…]()

# テスト項目

-　ステージ登録時に同じステージを希望した時バリデーションが発動する
- ステージ編集時に同じステージを希望した時バリデーションが発動する

# 備考

2023-05-20 05:40 UTC, YushiroDodo63 requested changes
@TsubasaOura 
これって `希望なし` を選択した時ってエラー文出さないようにするんじゃなかったっけ？

2023-05-20 05:41 UTC, TsubasaOura commented
あ！それできてないかも
ごめん修正します

2023-05-20 08:42 UTC, TsubasaOura commented
へんこうしました！

2023-05-20 15:28 UTC, TsubasaOura commented
修正いたしました！

2023-05-21 01:22 UTC, ryuseifujisaki requested changes
バリデーションはできてた！
ただ、登録しても表示されていないぽい?
developにmergeしたら表示されるんかな？
![image](https://github.com/NUTFes/group-manager-2/assets/50622120/38e28b2f-96af-4044-9866-3685f5f94b98)

2023-05-21 09:36 UTC, TsubasaOura commented
@imaimai17468 
修正しました！
テスト項目を追記したので確認お願いします！

2023-05-21 13:13 UTC, ryuseifujisaki commented
😭 
![image](https://github.com/NUTFes/group-manager-2/assets/50622120/49e20497-536d-4d9e-a5a8-d885ff86554e)

2023-05-21 13:20 UTC, ryuseifujisaki commented
😭 
![image](https://github.com/NUTFes/group-manager-2/assets/50622120/e4162ae2-07ea-46c9-ad97-4d117f356c75)

2023-05-21 13:24 UTC, TsubasaOura commented
もう一度　force push しました

2023-05-21 13:28 UTC, ryuseifujisaki commented
@TsubasaOura 
動作問題なしです!
Mergeします

2023-05-21 13:28 UTC, merged