[wip]mypageに戻るようにする
NUTFes/group-manager-2 pull request #1230
Opened 2023-05-23 01:44 UTC by harata-t

# 対応Issue

resolve #1223 

# 概要

- 各ページでボタンを押したときにmypageに飛ぶようにする
- 成功か失敗かの通知を出す

# 変更ファイル

- user_front/pages/mypage/edit_group/index.vue
- user_front/pages/mypage/password_reset/index.vue
- user_front/pages/regist/announcement/index.vue
- user_front/pages/regist/publicRelations/index.vue
- user_front/pages/regist/venueMap/index.vue

# 画面スクリーンショット等

- `URL`
スクリーンショット
![image](https://github.com/NUTFes/group-manager-2/assets/107479066/9fc30071-8cc5-437b-9920-e4c5d9c3f964)

# テスト項目

- http://localhost:8002/mypage/edit_group→編集→http://localhost:8002/mypageに飛ぶ
- http://localhost:8002/mypage/password_reset → register　→ http://localhost:8002/mypage
- http://localhost:8002/regist/announcement→register→http://localhost:8002/mypage
- http://localhost:8002/regist/venueMap→register→http://localhost:8002/mypage
- http://localhost:8002/mypage/password_reset → register　→http://localhost:8002/mypage
-
-

# 備考
- PR登録と会場配置図登録だけ2回押さないとmypageに飛ばない
- 成功か失敗かの通知機能はまだできていない

2023-05-24 14:55 UTC, imaimai17468 requested changes
動作は確認OKですが、超微修正と、コンフリクトの解消をお願いします！

2023-05-24 14:55 UTC, imaimai17468 commented on user_front/pages/regist/venueMap/index.vue
> +  // router.push("/myPage");
不要なコメントは消しておこう

2023-05-24 15:20 UTC, imaimai17468 approved these changes
LGTM!!

2023-05-24 17:53 UTC, ryuseifujisaki commented
@harata-t @imaimai17468 
- 会場配置図登録してもmypage戻らなくない？
- てか鼻から登録できてなさそう

2023-05-25 00:52 UTC, harata-t commented
@ryuseifujisaki 
会場配置図登録とPR登録に関しては2回押さないと登録できないですね
一応api立ち上げて確認してみるとpostできてると思います
<img width="960" alt="image" src="https://github.com/NUTFes/group-manager-2/assets/107479066/70a805fc-8f3c-4fb6-bda8-0e80dd6a7674">

2023-05-25 07:52 UTC, merged