模擬店平面図のAPI作成とページの作成
NUTFes/group-manager-2 pull request #1634
Opened 2024-05-22 18:15 UTC by hikahana

# 対応Issue

resolve #1485

# 概要

- PRか参加団体申請かどこかで平面図を表示させていたが独立した模擬店平面図ページを作成することにした。

# 実装詳細

- 何をいじったのか忘れた
- venue_maps_controller作った
- menu.vueにvenue_mapを追加した
- role全てにvenue_mapを追加した。(後で書く)
- venue_maps.vue,_id.vue作った。
- あとは後で書く

# 画面スクリーンショット等

![image](https://github.com/NUTFes/group-manager-2/assets/106811268/d268b20d-d6f6-4a8b-812c-d6f97ca84683)
![image](https://github.com/NUTFes/group-manager-2/assets/106811268/3a3633cd-2eb0-4dea-b117-b34987422d24)

# テスト項目

- [ ] ページが表示できるか
- [ ] 一覧ページで追加できるか、追加された場合文面が登録済みに代わるか
- [ ] 詳細ページで編集できるか、編集できた場合編集された情報が表示されるか
- [ ] 詳細ページで削除できるか、削除できた場合文面が**未登録**がになるか
- [ ] roleによって操作権限が変わっているか
- [ ] あと分からん

# 備考

public_relatonみたりannouncement見たりcooking_process_orderを見たりしているのですごくコードが汚いです。
大変ですがコードレビューもお願いしたいです。。。。。

2024-05-23 09:55 UTC, sota1024 requested changes
- 一覧ページからの変更ができませんでした。
- ファイル選択でpdfを入れるとエラーを出すようにした方がいいのでは！？

2024-05-24 10:47 UTC, hikahana commented
@sota1024 修正しました。
- 一覧ページでpost処理の修正
- 一覧、詳細それぞれに[.png,.jpeg]以外でのファイルの時メッセージを出現させる。なおかつボタンにdisabledを付与

2024-05-29 02:37 UTC, harata-t reviewed
@hikahana 
- [バグ] 一覧ページの追加モーダルからファイルなしで登録できる
- [バグ] 詳細ページの編集モーダルからファイルなしで登録すると`An error occurred`が起こる
- [追加] ファイル名が「参加形式_団体名」になっているかのバリデーションかけて欲しい🥺
  - 一覧ページの追加モーダル
  - 詳細ページの編集モーダル
  - ユーザー画面の模擬店平面図登録ページ

2024-06-03 18:33 UTC, hikahana commented
> @hikahana
> 
> * [バグ] 一覧ページの追加モーダルからファイルなしで登録できる
> * [バグ] 詳細ページの編集モーダルからファイルなしで登録すると`An error occurred`が起こる
> * [追加] ファイル名が「参加形式_団体名」になっているかのバリデーションかけて欲しい🥺
>   
>   * 一覧ページの追加モーダル
>   * 詳細ページの編集モーダル
>   * ユーザー画面の模擬店平面図登録ページ

修正しました。
一覧・詳細ページ双方で新たにisFile,isFileCheckの変数を設けました。
画像ファイル形式と「参加団体_団体名」のバリデーションチェックを行い問題がない場合isFileをtrueにし、それでボタンのdisabledを解除するようにしました。

他にもjpegだけでなくjpg形式にも対応できるようにしました。

ボタンにdisabledがかかっているときはフォーカスを当ててもボタンの色が変化しないようにしました

2024-06-11 09:37 UTC, harata-t reviewed
@hikahana 
微修正頼んだ

2024-06-11 09:37 UTC, harata-t commented on user_front/pages/mypage/publicRelations/index.vue
> +    if (!["image/jpeg", "image/png", "image/png"].includes(selectedFile.value.type)) {
```suggestion
    if (!["image/jpeg", "image/png"].includes(selectedFile.value.type)) {
```
同じの追加されてるから元に戻していいかも

2024-06-11 09:37 UTC, harata-t commented on api/app/controllers/venue_maps_controller.rb
> +      params.require(:venue_map).permit(:group_id, :picture_name, :picture_path)
```suggestion
      params.permit(:group_id, :picture_name, :picture_path)
```
ユーザー画面からの新規登録ができなくなるから応急処置としてrequireは消した方いいかも
あとで何が正しい方法なのか模索してみる

2024-06-11 11:46 UTC, harata-t approved these changes
lgtm

2024-06-11 11:59 UTC, sota1024 approved these changes
よさ

2024-06-11 12:00 UTC, merged